version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.5'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:5.5.3'
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  kafka-ui:
    image: 'provectuslabs/kafka-ui'
    container_name: 'kafka-ui'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_MAXPARTITIONSFETCH=500
      - KAFKA_CLUSTERS_0_FILTERLOGS=true